name: bad_words_moderator
description: "Flutter widget and functions to filter bad words from input text."
version: 0.1.0
homepage: https://github.com/jigordev/bad_words_moderator
repository: https://github.com/jigordev/bad_words_moderator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/wordlist.txt
